apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgbot
  template:
    metadata:
      labels:
        app: tgbot
    spec:
      containers:
        - name: tgbot
          image: cr.yandex/crpsdtfa3vma0tp41r1e/tgbot:1.0.8
          imagePullPolicy: Always